### ISSUE TITLE
Spacing Issues in Admin Tools  [Moodle 4.0beta+]

### ISSUE THREAD

**Issue by aaronkossler** [learnweb/moodle-theme_wwu2019#101]
No automatic spacing between borders and content. Issue applies to admin tools/plugins only as far as I can tell.
![image](https://user-images.githubusercontent.com/74201118/160426269-d97684d0-4d79-4338-9648-d158893eea35.png)

**Comment by aaronkossler** [comment]
Also applies to the Manage Courses Page.
![image](https://user-images.githubusercontent.com/74201118/160447956-75f22c5f-73c2-481d-9c7f-505fd48935fb.png)

**Comment by justusdieckmann** [comment]
Fixed by #106
