### ISSUE TITLE
Expand currently relevant submenu in settings menu

### ISSUE THREAD

**Issue by tobiasreischmann** [learnweb/moodle-theme_wwu2019#41]
Currently, all submenus are closed as default. In our previous version, the most relevant settings menu, was already expanded. This means when you are within the course, this would be the course administration. When you are in an activity the activity administration.

I think the nav tree that moodle serves comes already with an expanded flag or something.

**Comment by Dagefoerde** [comment]
As an extension:

When you are on an admin settings page, the entire menu path leading to the page should be expanded, as it was on theme_essential. Quite possibly, the flag that Tobias has mentioned is already set accordingly.
